/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReproductionsRouteImport } from './routes/reproductions'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PigeonsRouteImport } from './routes/pigeons'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExitsRouteImport } from './routes/exits'
import { Route as CouplesRouteImport } from './routes/couples'
import { Route as CagesRouteImport } from './routes/cages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReproductionsIndexRouteImport } from './routes/reproductions.index'
import { Route as PigeonsIndexRouteImport } from './routes/pigeons.index'
import { Route as ExitsIndexRouteImport } from './routes/exits.index'
import { Route as CouplesIndexRouteImport } from './routes/couples.index'
import { Route as CagesIndexRouteImport } from './routes/cages.index'
import { Route as ReproductionsIdRouteImport } from './routes/reproductions.$id'
import { Route as PigeonsRingRouteImport } from './routes/pigeons.$ring'
import { Route as ExitsIdRouteImport } from './routes/exits.$id'
import { Route as CouplesIdRouteImport } from './routes/couples.$id'
import { Route as CagesCodeRouteImport } from './routes/cages.$code'

const ReproductionsRoute = ReproductionsRouteImport.update({
  id: '/reproductions',
  path: '/reproductions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PigeonsRoute = PigeonsRouteImport.update({
  id: '/pigeons',
  path: '/pigeons',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitsRoute = ExitsRouteImport.update({
  id: '/exits',
  path: '/exits',
  getParentRoute: () => rootRouteImport,
} as any)
const CouplesRoute = CouplesRouteImport.update({
  id: '/couples',
  path: '/couples',
  getParentRoute: () => rootRouteImport,
} as any)
const CagesRoute = CagesRouteImport.update({
  id: '/cages',
  path: '/cages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReproductionsIndexRoute = ReproductionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReproductionsRoute,
} as any)
const PigeonsIndexRoute = PigeonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PigeonsRoute,
} as any)
const ExitsIndexRoute = ExitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExitsRoute,
} as any)
const CouplesIndexRoute = CouplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CouplesRoute,
} as any)
const CagesIndexRoute = CagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CagesRoute,
} as any)
const ReproductionsIdRoute = ReproductionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReproductionsRoute,
} as any)
const PigeonsRingRoute = PigeonsRingRouteImport.update({
  id: '/$ring',
  path: '/$ring',
  getParentRoute: () => PigeonsRoute,
} as any)
const ExitsIdRoute = ExitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExitsRoute,
} as any)
const CouplesIdRoute = CouplesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CouplesRoute,
} as any)
const CagesCodeRoute = CagesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cages': typeof CagesRouteWithChildren
  '/couples': typeof CouplesRouteWithChildren
  '/exits': typeof ExitsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/pigeons': typeof PigeonsRouteWithChildren
  '/profil': typeof ProfilRoute
  '/reproductions': typeof ReproductionsRouteWithChildren
  '/cages/$code': typeof CagesCodeRoute
  '/couples/$id': typeof CouplesIdRoute
  '/exits/$id': typeof ExitsIdRoute
  '/pigeons/$ring': typeof PigeonsRingRoute
  '/reproductions/$id': typeof ReproductionsIdRoute
  '/cages/': typeof CagesIndexRoute
  '/couples/': typeof CouplesIndexRoute
  '/exits/': typeof ExitsIndexRoute
  '/pigeons/': typeof PigeonsIndexRoute
  '/reproductions/': typeof ReproductionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/cages/$code': typeof CagesCodeRoute
  '/couples/$id': typeof CouplesIdRoute
  '/exits/$id': typeof ExitsIdRoute
  '/pigeons/$ring': typeof PigeonsRingRoute
  '/reproductions/$id': typeof ReproductionsIdRoute
  '/cages': typeof CagesIndexRoute
  '/couples': typeof CouplesIndexRoute
  '/exits': typeof ExitsIndexRoute
  '/pigeons': typeof PigeonsIndexRoute
  '/reproductions': typeof ReproductionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cages': typeof CagesRouteWithChildren
  '/couples': typeof CouplesRouteWithChildren
  '/exits': typeof ExitsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/pigeons': typeof PigeonsRouteWithChildren
  '/profil': typeof ProfilRoute
  '/reproductions': typeof ReproductionsRouteWithChildren
  '/cages/$code': typeof CagesCodeRoute
  '/couples/$id': typeof CouplesIdRoute
  '/exits/$id': typeof ExitsIdRoute
  '/pigeons/$ring': typeof PigeonsRingRoute
  '/reproductions/$id': typeof ReproductionsIdRoute
  '/cages/': typeof CagesIndexRoute
  '/couples/': typeof CouplesIndexRoute
  '/exits/': typeof ExitsIndexRoute
  '/pigeons/': typeof PigeonsIndexRoute
  '/reproductions/': typeof ReproductionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cages'
    | '/couples'
    | '/exits'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/parametres'
    | '/pigeons'
    | '/profil'
    | '/reproductions'
    | '/cages/$code'
    | '/couples/$id'
    | '/exits/$id'
    | '/pigeons/$ring'
    | '/reproductions/$id'
    | '/cages/'
    | '/couples/'
    | '/exits/'
    | '/pigeons/'
    | '/reproductions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/parametres'
    | '/profil'
    | '/cages/$code'
    | '/couples/$id'
    | '/exits/$id'
    | '/pigeons/$ring'
    | '/reproductions/$id'
    | '/cages'
    | '/couples'
    | '/exits'
    | '/pigeons'
    | '/reproductions'
  id:
    | '__root__'
    | '/'
    | '/cages'
    | '/couples'
    | '/exits'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/parametres'
    | '/pigeons'
    | '/profil'
    | '/reproductions'
    | '/cages/$code'
    | '/couples/$id'
    | '/exits/$id'
    | '/pigeons/$ring'
    | '/reproductions/$id'
    | '/cages/'
    | '/couples/'
    | '/exits/'
    | '/pigeons/'
    | '/reproductions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CagesRoute: typeof CagesRouteWithChildren
  CouplesRoute: typeof CouplesRouteWithChildren
  ExitsRoute: typeof ExitsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ParametresRoute: typeof ParametresRoute
  PigeonsRoute: typeof PigeonsRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  ReproductionsRoute: typeof ReproductionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reproductions': {
      id: '/reproductions'
      path: '/reproductions'
      fullPath: '/reproductions'
      preLoaderRoute: typeof ReproductionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pigeons': {
      id: '/pigeons'
      path: '/pigeons'
      fullPath: '/pigeons'
      preLoaderRoute: typeof PigeonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exits': {
      id: '/exits'
      path: '/exits'
      fullPath: '/exits'
      preLoaderRoute: typeof ExitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couples': {
      id: '/couples'
      path: '/couples'
      fullPath: '/couples'
      preLoaderRoute: typeof CouplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cages': {
      id: '/cages'
      path: '/cages'
      fullPath: '/cages'
      preLoaderRoute: typeof CagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reproductions/': {
      id: '/reproductions/'
      path: '/'
      fullPath: '/reproductions/'
      preLoaderRoute: typeof ReproductionsIndexRouteImport
      parentRoute: typeof ReproductionsRoute
    }
    '/pigeons/': {
      id: '/pigeons/'
      path: '/'
      fullPath: '/pigeons/'
      preLoaderRoute: typeof PigeonsIndexRouteImport
      parentRoute: typeof PigeonsRoute
    }
    '/exits/': {
      id: '/exits/'
      path: '/'
      fullPath: '/exits/'
      preLoaderRoute: typeof ExitsIndexRouteImport
      parentRoute: typeof ExitsRoute
    }
    '/couples/': {
      id: '/couples/'
      path: '/'
      fullPath: '/couples/'
      preLoaderRoute: typeof CouplesIndexRouteImport
      parentRoute: typeof CouplesRoute
    }
    '/cages/': {
      id: '/cages/'
      path: '/'
      fullPath: '/cages/'
      preLoaderRoute: typeof CagesIndexRouteImport
      parentRoute: typeof CagesRoute
    }
    '/reproductions/$id': {
      id: '/reproductions/$id'
      path: '/$id'
      fullPath: '/reproductions/$id'
      preLoaderRoute: typeof ReproductionsIdRouteImport
      parentRoute: typeof ReproductionsRoute
    }
    '/pigeons/$ring': {
      id: '/pigeons/$ring'
      path: '/$ring'
      fullPath: '/pigeons/$ring'
      preLoaderRoute: typeof PigeonsRingRouteImport
      parentRoute: typeof PigeonsRoute
    }
    '/exits/$id': {
      id: '/exits/$id'
      path: '/$id'
      fullPath: '/exits/$id'
      preLoaderRoute: typeof ExitsIdRouteImport
      parentRoute: typeof ExitsRoute
    }
    '/couples/$id': {
      id: '/couples/$id'
      path: '/$id'
      fullPath: '/couples/$id'
      preLoaderRoute: typeof CouplesIdRouteImport
      parentRoute: typeof CouplesRoute
    }
    '/cages/$code': {
      id: '/cages/$code'
      path: '/$code'
      fullPath: '/cages/$code'
      preLoaderRoute: typeof CagesCodeRouteImport
      parentRoute: typeof CagesRoute
    }
  }
}

interface CagesRouteChildren {
  CagesCodeRoute: typeof CagesCodeRoute
  CagesIndexRoute: typeof CagesIndexRoute
}

const CagesRouteChildren: CagesRouteChildren = {
  CagesCodeRoute: CagesCodeRoute,
  CagesIndexRoute: CagesIndexRoute,
}

const CagesRouteWithChildren = CagesRoute._addFileChildren(CagesRouteChildren)

interface CouplesRouteChildren {
  CouplesIdRoute: typeof CouplesIdRoute
  CouplesIndexRoute: typeof CouplesIndexRoute
}

const CouplesRouteChildren: CouplesRouteChildren = {
  CouplesIdRoute: CouplesIdRoute,
  CouplesIndexRoute: CouplesIndexRoute,
}

const CouplesRouteWithChildren =
  CouplesRoute._addFileChildren(CouplesRouteChildren)

interface ExitsRouteChildren {
  ExitsIdRoute: typeof ExitsIdRoute
  ExitsIndexRoute: typeof ExitsIndexRoute
}

const ExitsRouteChildren: ExitsRouteChildren = {
  ExitsIdRoute: ExitsIdRoute,
  ExitsIndexRoute: ExitsIndexRoute,
}

const ExitsRouteWithChildren = ExitsRoute._addFileChildren(ExitsRouteChildren)

interface PigeonsRouteChildren {
  PigeonsRingRoute: typeof PigeonsRingRoute
  PigeonsIndexRoute: typeof PigeonsIndexRoute
}

const PigeonsRouteChildren: PigeonsRouteChildren = {
  PigeonsRingRoute: PigeonsRingRoute,
  PigeonsIndexRoute: PigeonsIndexRoute,
}

const PigeonsRouteWithChildren =
  PigeonsRoute._addFileChildren(PigeonsRouteChildren)

interface ReproductionsRouteChildren {
  ReproductionsIdRoute: typeof ReproductionsIdRoute
  ReproductionsIndexRoute: typeof ReproductionsIndexRoute
}

const ReproductionsRouteChildren: ReproductionsRouteChildren = {
  ReproductionsIdRoute: ReproductionsIdRoute,
  ReproductionsIndexRoute: ReproductionsIndexRoute,
}

const ReproductionsRouteWithChildren = ReproductionsRoute._addFileChildren(
  ReproductionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CagesRoute: CagesRouteWithChildren,
  CouplesRoute: CouplesRouteWithChildren,
  ExitsRoute: ExitsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ParametresRoute: ParametresRoute,
  PigeonsRoute: PigeonsRouteWithChildren,
  ProfilRoute: ProfilRoute,
  ReproductionsRoute: ReproductionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
